export const HEALTH_CHECK = 'app/HEALTH_CHECK'
export const LOGIN = 'app/LOGIN'
export const REPORT_ISSUE = 'app/REPORT_ISSUE'
export const CONFIG_DEFAULT = 'app/CONFIG_DEFAULT'
export const CONFIG_DATA = 'app/CONFIG_DATA'
