// eslint-disable-next-line import/prefer-default-export
export const NAV_WELCOME = '/welcome'
export const NAV_TERMS = '/terms'
export const NAV_TERMS_VIEW = '/terms-view'
export const NAV_LOGIN = '/login'
export const NAV_DASHBOARD = '/dashboard'
export const NAV_SETTINGS = '/settings'
export const NAV_STATISTICS = '/statistics'
export const NAV_FAQ = '/faq'
export const NAV_PRIVACY_POLICY = '/privacy-policy'
