name: Main
on:
  push:
    tags:
      - '*'
  pull_request:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.19.0

      - name: 'Install dependencies'
        run: yarn

      - name: 'Build app'
        run: yarn build

  test:
    name: 'Test'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.19.0

      - name: 'Install dependencies'
        run: yarn

      - name: 'Run tests'
        run: yarn test

  publish:
    name: 'Publish ${{ github.ref_name }}'
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [ build, test ]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.19.0

      - name: 'Update package.json version to ${{ github.ref_name }}'
        run: |
          jq --arg tag "${{ github.ref_name }}" '.version=(if $tag == "refs/heads/master" then "0.0.0-snapshot" else $tag end)' package.json > package.json.mod
          mv package.json.mod package.json

      - name: 'Install dependencies'
        run: yarn

      - name: 'Build app'
        run: yarn build

      - name: 'Prepare assets ${{ github.ref_name }}'
        run: tar -zcvf dist.tar.gz build/

      - name: 'Publish assets ${{ github.ref_name }}'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist.tar.gz
            compatibility.json
